services:
    miisieq.version_strategy.gulp_buster:
        class: Miisieq\VersionStrategyBundle\Asset\VersionStrategy\GulpBusterVersionStrategy
        arguments:
            - "%kernel.root_dir%/../busters.json"
            - "%kernel.root_dir%"
            - "%%s?version=%%s"
        public: false